// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkQkxJnB2v-Sk3IVqNLyO6Rzn7sKgwSA',
    appId: '1:655946141578:web:2dd3aa3fcfd2fd63694273',
    messagingSenderId: '655946141578',
    projectId: 'cest-7e377',
    authDomain: 'cest-7e377.firebaseapp.com',
    databaseURL: 'https://cest-7e377-default-rtdb.firebaseio.com',
    storageBucket: 'cest-7e377.appspot.com',
    measurementId: 'G-ZZD4B7J324',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNckcl0BHFVDx4eZbKQ_Ff34ObU5yY18',
    appId: '1:655946141578:android:346616b0385753a4694273',
    messagingSenderId: '655946141578',
    projectId: 'cest-7e377',
    databaseURL: 'https://cest-7e377-default-rtdb.firebaseio.com',
    storageBucket: 'cest-7e377.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5i2EX3DJKKG4e5bnfu1UeIzqMcOrz9mk',
    appId: '1:655946141578:ios:05cc46aaad4fb8f0694273',
    messagingSenderId: '655946141578',
    projectId: 'cest-7e377',
    databaseURL: 'https://cest-7e377-default-rtdb.firebaseio.com',
    storageBucket: 'cest-7e377.appspot.com',
    iosClientId: '655946141578-brio6df74ec0ehr6l01g2oov9vqjlfl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ies.RunnerTests',
  );
}
